package com.devpulse.alertprocessor.model;

import com.devpulse.common.enums.AlertSeverity;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.Map;

/**
 * MongoDB document that stores alerts generated by:
 *  - Log-based alerting (via LogCollector)
 *  - Metrics-based alerting (via Prometheus queries)
 *
 * It stores both structured metadata and a flexible "context" field
 * allowing additional rule-specific information.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Document(collection = "alerts")
public class AlertDocument {

    @Id
    private String id;

    /** Associated service (producer-order, producer-product, etc.) */
    private String serviceName;

    /** Severity level (INFO, WARNING, CRITICAL) */
    private AlertSeverity severity;

    /** Human-readable alert message */
    private String message;

    /** Timestamp when alert occurred */
    private Instant timestamp;

    // Optional fields for log-based alerts
    private String traceId;
    private String ruleId;
    private String details;

    /**
     * Additional dynamic metadata (metric value, labels, thresholds).
     * Allows storing flexible information.
     */
    private Map<String, Object> context;
}